Feat/people
kixlab/website pull request #16
Opened 2024-02-29 06:21 UTC by shahnozayadgar

- I have included all current members in lab with their names, email address, pictures, and links to their personal websites. This page will be modified and improved more!
- Add a screenshot/video of the feature you developed (if applicable).
<img width="1173" alt="Screenshot 2024-02-29 at 3 20 44 PM" src="https://github.com/kixlab/website/assets/140824332/dbc9d242-54f3-43c6-8094-9aea0514698a">

2024-02-29 08:54 UTC, alextio approved these changes

2024-03-01 00:39 UTC, alextio requested changes
Noza's field in members.ts is missing email and career field causing errors in checks. Please add those.

2024-03-01 00:39 UTC, alextio commented on src/data/members.ts
> +    img: 'noza.jpeg',
Missing email, career field here

2024-03-06 14:00 UTC, jhw123 commented
Could you fix the type error first?

2024-03-21 11:52 UTC, alextio commented
Too many file changes. Best to restart this PR with a clean branch.

2024-03-21 11:52 UTC, closed without merging